services:

  axon-server:
    image: "axoniq/axonserver"
    ports:
      - "8024:8024"
      - "8214:8214"
    restart: always

  mongodb:
    image: "mongo:6-jammy"
    ports:
      - '27017:27017'

  postgresql:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
      - POSTGRES_DB=bank_db
    ports:
      - "5432:5432"